import Foundation
import CoreData

// Helper extensions for the ClassifiedPhoto entity generated by Core Data.

extension ClassifiedPhoto {
    /// Convenience fetch request for all photos sorted by timestamp (newest first).
    static func fetchAllSortedByDateRequest() -> NSFetchRequest<ClassifiedPhoto> {
        let request: NSFetchRequest<ClassifiedPhoto> = ClassifiedPhoto.fetchRequest()
        request.sortDescriptors = [
            NSSortDescriptor(key: "timestamp", ascending: false)
        ]
        return request
    }
}
